### ISSUE TITLE
Failed to copy asset file: ffmpeg

### ISSUE THREAD

**Issue by aizhimin** [codlab/android_screen#2]
03-27 10:40:49.436: E/tag(10641): java.io.IOException
03-27 10:40:49.436: E/tag(10641):   at android.content.res.AssetManager.readAsset(Native Method)
03-27 10:40:49.436: E/tag(10641):   at android.content.res.AssetManager.access$700(AssetManager.java:36)
03-27 10:40:49.436: E/tag(10641):   at android.content.res.AssetManager$AssetInputStream.read(AssetManager.java:571)
03-27 10:40:49.436: E/tag(10641):   at eu.codlab.screencast.AwesomeScreencastService.copyFile(AwesomeScreencastService.java:370)
03-27 10:40:49.436: E/tag(10641):   at eu.codlab.screencast.AwesomeScreencastService.copyFFMPEG(AwesomeScreencastService.java:339)
03-27 10:40:49.436: E/tag(10641):   at eu.codlab.screencast.AwesomeScreencastService.copyAssets(AwesomeScreencastService.java:329)
03-27 10:40:49.436: E/tag(10641):   at eu.codlab.screencast.AwesomeScreencastService.onStartCommand(AwesomeScreencastService.java:172)

**Comment by codlab** [comment]
it is an issue with the asset ffmpeg in the assets folder. It needs to be changed to ffmpeg.jpeg, ffmpeg.png etc... and changed in the source
